name: GitHub Actions DotNet
on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  Job-DotNet-Push:
    runs-on: ubuntu-latest
    env:
      DOTNET_CORE_VERSION: 3.1.x
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
      DOTNET_NOLOGO: true
      BUILD_CONFIGURATION: Release
      PROJECT_PATH: /WebApplication1
  steps:
    - name: Check out repository code ('${{github.repository}}' cloned to the runner)
      uses: actions/checkout@v1
     
